set(MUSA_ARCHS mp_31)
set(MUSA_MCC_FLAGS -x musa -fgpu-rdc --offload-arch=${MUSA_ARCHS} -resource-usage)

if (DEFINED ENV{MCC_EXTRA_ARGS})
    foreach(arg  $ENV{MCC_EXTRA_ARGS})
        message("MCC_EXTRA_ARGS: ${arg}")
        list(APPEND MUSA_MCC_FLAGS ${arg})
    endforeach()
endif()

set(_DEFAULT_NVSHMEM_ROOT_DIR "/usr/local/mtshmem")
if(DEFINED ENV{NVSHMEM_ROOT_DIR})
    set(_DEFAULT_NVSHMEM_ROOT_DIR "$ENV{NVSHMEM_ROOT_DIR}")
endif()
set(NVSHMEM_ROOT_DIR "${_DEFAULT_NVSHMEM_ROOT_DIR}" CACHE PATH "NVSHMEM ROOT DIR")
unset(_DEFAULT_NVSHMEM_ROOT_DIR)
message("NVSHMEM_ROOT_DIR :${NVSHMEM_ROOT_DIR}")

set(_DEFAULT_MUSA_PATH "/usr/local/musa")
if(DEFINED ENV{MUSA_PATH})
    set(_DEFAULT_MUSA_PATH "$ENV{MUSA_PATH}")
endif()
set(MUSA_PATH "${_DEFAULT_MUSA_PATH}" CACHE PATH "MUSA PATH")
unset(_DEFAULT_MUSA_PATH)
message("MUSA_PATH :${MUSA_PATH}")

set(_DEFAULT_PYTHON_PACKAGE_PATH "/usr/local/lib/python3.10/dist-packages")
if(DEFINED ENV{PYTHON_PACKAGE_PATH})
    set(_DEFAULT_PYTHON_PACKAGE_PATH "$ENV{PYTHON_PACKAGE_PATH}")
endif()
set(PYTHON_PACKAGE_PATH "${_DEFAULT_PYTHON_PACKAGE_PATH}" CACHE PATH "PYTHON PACKAGE PATH")
unset(_DEFAULT_PYTHON_PACKAGE_PATH)
message("PYTHON_PACKAGE_PATH: ${PYTHON_PACKAGE_PATH}")

set(_DEFAULT_ENABLE_TIMEOUT_CHECK "OFF")
if(DEFINED ENV{ENABLE_TIMEOUT_CHECK})
    set(_DEFAULT_ENABLE_TIMEOUT_CHECK "$ENV{ENABLE_TIMEOUT_CHECK}")
endif()
set(ENABLE_TIMEOUT_CHECK "${_DEFAULT_ENABLE_TIMEOUT_CHECK}" CACHE PATH "ENABLE TIMEOUT CHECK")
unset(_DEFAULT_ENABLE_TIMEOUT_CHECK)
message("ENABLE_TIMEOUT_CHECK: ${ENABLE_TIMEOUT_CHECK}")

if(ENABLE_TIMEOUT_CHECK)
    list(APPEND MUSA_MCC_FLAGS -DENABLE_TIMEOUT_CHECK)
endif()

set(NCCL_ROOT_DIR ${MUSA_PATH})

list(APPEND CMAKE_MODULE_PATH "${MUSA_PATH}/cmake")
list(APPEND CMAKE_PREFIX_PATH "${PYTHON_PACKAGE_PATH}/torch/share/cmake/Torch")
set(pybind11_DIR "${PYTHON_PACKAGE_PATH}/pybind11/share/cmake/pybind11")
set(TorchMusa_DIR "${PYTHON_PACKAGE_PATH}/torch_musa/share/cmake/TorchMusa")
find_package(pybind11 REQUIRED)
find_package(MUSAToolkit REQUIRED)

find_library(TorchMusa_LIBRARY REQUIRED NAMES musa_python PATHS "${PYTHON_PACKAGE_PATH}/torch_musa/lib" REQUIRED)
list(APPEND TorchMusa_LIBRARIES ${TorchMusa_LIBRARY})

find_library(MusaKernels_LIBRARY REQUIRED NAMES musa_kernels PATHS "${PYTHON_PACKAGE_PATH}/torch_musa/lib" REQUIRED)
list(APPEND TorchMusa_LIBRARIES ${MusaKernels_LIBRARY})

set(MUSA_INCLUDE_DIR ${MUSAToolkit_TARGET_DIR}/include)
set(MUDNN_INCLUDE_DIR ${MUSA_INCLUDE_DIR}/mudnncxx)
include_directories(deep_ep/include/musa ${MUDNN_INCLUDE_DIR} ${MUSA_INCLUDE_DIR} ${PYTHON_PACKAGE_PATH})
link_directories(${MUSAToolkit_TARGET_DIR}/lib)

find_library(MUSART_LIB musart PATHS "${MUSA_PATH}/lib" REQUIRED)
add_library(musart SHARED IMPORTED)
set_target_properties(musart PROPERTIES
    IMPORTED_LOCATION "${MUSART_LIB}"
)
add_library(cudart ALIAS musart)

set(CMAKE_CXX_CREATE_SHARED_MODULE
  "${MUSA_PATH}/bin/mcc <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>"
)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)